### ISSUE TITLE
Where to put python modules?

### ISSUE THREAD

**Issue by drakeguan** [wdas/partio#33]
I noticed that the installed directory for python modules (`_partio.so` and `partio.py`) are in `~/lib64/`, which might be unusual in some OS. I will suggest to install to `~/lib` directly, even in 64bit OS cause in those 64bit environment, `~/lib64` is a symbolic link to `~/lib`, and there is another `~/lib32` for 32bits libraries. But in Mac OSX and other 32bit OS, there is no ~/lib64`, which makes the installation error.

**Comment by davvid** [comment]
I believe this should already be resolved. We are using GNUInstallDirs so you should get the default `lib` by default when on macOS and other platforms where `lib` is the convention.

https://github.com/wdas/partio/blob/master/CMakeLists.txt#L88

If that's not sufficient, you can set the `CMAKE_INSTALL_LIBDIR` variable to a relative path and it'll use that instead of `lib` (or `lib64`).
