### ISSUE TITLE
how can i compile it with python3.7 in ubuntu20.04

### ISSUE THREAD

**Issue by zqhfox** [wdas/partio#86]
how can i install it with pip3? or get a ".whl" file?

**Comment by davvid** [comment]
Hello, we don't currently have a pip release.  That said, the repo is designed to be able to be installed into a virtualenv, and does build under python3, so that might be the simplest path forward.

For example, from the partio repo let's assume that I'm going to create a python3.7 virtualenv and then install partio into it.  I'm using https://github.com/davvid/vx but you can play the activate/deactivate dance instead as well.


```
# create the python3.7 virtualenv in a subdirectory called "env37"
python3.7 -m venv env37

# install partio into the virtualenv
vx env37 make install prefix=$PWD/env37

# verify that we can import the module
vx env37 python -c 'import partio; print(partio)'

# verify that the listAttr.py example works
vx env37 python ./src/py/example/listAttr.py ./src/data/test.geo
```
